### ISSUE TITLE
windows工程化的建议

### ISSUE THREAD

**Issue by lion117** [cyz7758520/Windows_audio_talkback_demo_program#2]
1. vs 的路径名太长, vs无法正常打开. 
2. 基于VS的库编译存在 MD/MT, DEBUG/RELEASE等组合差异. 二进制库无法链接到实际的工程中去.  如果只想提供 release版本的库, 建议用cmake+clang编译.  MT/MTD 运行时库很少实际的工程中使用.  
3. 算法库本质上不依赖func库, 强行耦合在一起. 增加复杂度. 如果需要抛出复杂错误信息. 可以用json的方式抛出.

**Comment by cyz7758520** [comment]
您好。
1、你的路径有多长呢？能发上来看看不？
2、你这个无法链接是报什么错呢？
3、算法库本质上是不依赖，但是我有做很多优化，加入了我自己的代码，所有需要依赖，这个应该不影响你的工程的，报错改为json那是不是也增加了复杂度？

能加个QQ吗？我的：280604597。
